using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using AssemblyScannerSample.EnumBase;

namespace AssemblyScannerSample.SampleAllOptionConsumer
{
    /// <summary>
    /// Collection of all option values.
    /// </summary>
    public static class Options
    {
        /// <summary>
        /// Gets all available options.
        /// </summary>
        public static ImmutableArray<ScanOptionEnumBase> All { get; } = ImmutableArray.Create<ScanOptionEnumBase>(
            // This would normally be generated by the source generator
            // We're creating it manually as a workaround
            new EnumLibrary1.OptionAlpha(),
            new EnumLibrary2.OptionBeta()
        );
    }
}
