<#
.SYNOPSIS
    Gets the version that would be generated by Nerdbank.GitVersioning for the EnhancedEnums project.
.DESCRIPTION
    This script uses nbgv (Nerdbank.GitVersioning) to show what version would be calculated
    for the EnhancedEnums project based on the current git state.
.EXAMPLE
    .\Get-Version.ps1
#>

# Repository root (two levels up from samples/AssemblyScanner)
$repoRoot = Join-Path $PSScriptRoot '..\..'
$enhancedEnumsProj = Join-Path $repoRoot 'src\DomesticatedData.EnhancedEnums\DomesticatedData.EnhancedEnums.csproj'
$enhancedEnumsDir = Join-Path $repoRoot 'src\DomesticatedData.EnhancedEnums'

Write-Host "Checking version for: $enhancedEnumsProj" -ForegroundColor Cyan
Write-Host ""

# Check if nbgv is installed
$nbgvInstalled = $null -ne (Get-Command nbgv -ErrorAction SilentlyContinue)
if (!$nbgvInstalled) {
    Write-Host "nbgv tool not found. Installing globally..." -ForegroundColor Yellow
    dotnet tool install -g nbgv
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to install nbgv tool"
        exit 1
    }
}

# Change to the project directory to get accurate version info
Push-Location $enhancedEnumsDir
try {
    Write-Host "Getting version information from Nerdbank.GitVersioning:" -ForegroundColor Green
    Write-Host ""
    
    # Get detailed version info
    nbgv get-version
    
    Write-Host ""
    Write-Host "Key version properties:" -ForegroundColor Green
    Write-Host "- NuGet Package Version: " -NoNewline
    Write-Host (nbgv get-version -v NuGetPackageVersion) -ForegroundColor Yellow
    Write-Host "- Assembly Version: " -NoNewline
    Write-Host (nbgv get-version -v AssemblyVersion) -ForegroundColor Yellow
    Write-Host "- Assembly File Version: " -NoNewline
    Write-Host (nbgv get-version -v AssemblyFileVersion) -ForegroundColor Yellow
    Write-Host "- Assembly Informational Version: " -NoNewline
    Write-Host (nbgv get-version -v AssemblyInformationalVersion) -ForegroundColor Yellow
    
    Write-Host ""
    Write-Host "This is the version that will be used when packing without -p:PackageVersion override" -ForegroundColor Cyan
}
finally {
    Pop-Location
}